#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
# and adjusted manually by josemars@ifes.edu.br                                #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -I/usr/debug/include/opencv4 -I/usr/debug/include/opencv4/opencv2 -I../v4l2misc -I../kbhit
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -L/usr/debug/lib
LIB_DEBUG = $(LIB)-lpthread -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_calib3d -lopencv_ccalib -lopencv_core -lopencv_datasets -lopencv_dnn -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_features2d -lopencv_flann -lopencv_freetype -lopencv_fuzzy -lopencv_gapi -lopencv_hfs -lopencv_highgui -lopencv_img_hash -lopencv_imgcodecs -lopencv_imgproc -lopencv_line_descriptor -lopencv_ml -lopencv_objdetect -lopencv_optflow -lopencv_phase_unwrapping -lopencv_photo -lopencv_plot -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_stitching -lopencv_structured_light -lopencv_superres -lopencv_surface_matching -lopencv_text -lopencv_tracking -lopencv_video -lopencv_videoio -lopencv_videostab -lopencv_xfeatures2d -lopencv_ximgproc -lopencv_xobjdetect -lopencv_xphoto
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = ./object/Debug
DEP_DEBUG = 
OUT_DEBUG = ./bin/Debug/Multiview

INC_RELEASE = $(INC) -I/usr/local/include/opencv4 -I/usr/local/include/opencv4/opencv2 -I../v4l2misc -I../kbhit
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -L/usr/local/lib
LIB_RELEASE = $(LIB)-lpthread -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_calib3d -lopencv_ccalib -lopencv_core -lopencv_datasets -lopencv_dnn -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_features2d -lopencv_flann -lopencv_freetype -lopencv_fuzzy -lopencv_gapi -lopencv_hfs -lopencv_highgui -lopencv_img_hash -lopencv_imgcodecs -lopencv_imgproc -lopencv_line_descriptor -lopencv_ml -lopencv_objdetect -lopencv_optflow -lopencv_phase_unwrapping -lopencv_photo -lopencv_plot -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_stitching -lopencv_structured_light -lopencv_superres -lopencv_surface_matching -lopencv_text -lopencv_tracking -lopencv_video -lopencv_videoio -lopencv_videostab -lopencv_xfeatures2d -lopencv_ximgproc -lopencv_xobjdetect -lopencv_xphoto
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = ./object/Release
DEP_RELEASE = 
OUT_RELEASE = ./bin/Release/Multiview

OBJ_DEBUG = $(OBJDIR_DEBUG)/Multiview/src/process004.o $(OBJDIR_DEBUG)/Multiview/src/process003.o $(OBJDIR_DEBUG)/Multiview/src/process002.o $(OBJDIR_DEBUG)/Multiview/src/process001.o $(OBJDIR_DEBUG)/kbhit/kbhit.o $(OBJDIR_DEBUG)/Multiview/src/process000.o $(OBJDIR_DEBUG)/Multiview/src/multiview.o $(OBJDIR_DEBUG)/v4l2misc/v4l2misc.o $(OBJDIR_DEBUG)/v4l2misc/camview.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/Multiview/src/process004.o $(OBJDIR_RELEASE)/Multiview/src/process003.o $(OBJDIR_RELEASE)/Multiview/src/process002.o $(OBJDIR_RELEASE)/Multiview/src/process001.o $(OBJDIR_RELEASE)/kbhit/kbhit.o $(OBJDIR_RELEASE)/Multiview/src/process000.o $(OBJDIR_RELEASE)/Multiview/src/multiview.o $(OBJDIR_RELEASE)/v4l2misc/v4l2misc.o $(OBJDIR_RELEASE)/v4l2misc/camview.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d ./bin/Debug || mkdir -p ./bin/Debug
	test -d $(OBJDIR_DEBUG)/Multiview/src || mkdir -p $(OBJDIR_DEBUG)/Multiview/src
	test -d $(OBJDIR_DEBUG)/kbhit || mkdir -p $(OBJDIR_DEBUG)/kbhit
	test -d $(OBJDIR_DEBUG)/v4l2misc || mkdir -p $(OBJDIR_DEBUG)/v4l2misc

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/Multiview/src/process004.o: src/process004.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/process004.cpp -o $(OBJDIR_DEBUG)/Multiview/src/process004.o

$(OBJDIR_DEBUG)/Multiview/src/process003.o: src/process003.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/process003.cpp -o $(OBJDIR_DEBUG)/Multiview/src/process003.o

$(OBJDIR_DEBUG)/Multiview/src/process002.o: src/process002.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/process002.cpp -o $(OBJDIR_DEBUG)/Multiview/src/process002.o

$(OBJDIR_DEBUG)/Multiview/src/process001.o: src/process001.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/process001.cpp -o $(OBJDIR_DEBUG)/Multiview/src/process001.o

$(OBJDIR_DEBUG)/kbhit/kbhit.o: ../kbhit/kbhit.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../kbhit/kbhit.c -o $(OBJDIR_DEBUG)/kbhit/kbhit.o

$(OBJDIR_DEBUG)/Multiview/src/process000.o: src/process000.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/process000.cpp -o $(OBJDIR_DEBUG)/Multiview/src/process000.o

$(OBJDIR_DEBUG)/Multiview/src/multiview.o: src/multiview.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/multiview.cpp -o $(OBJDIR_DEBUG)/Multiview/src/multiview.o

$(OBJDIR_DEBUG)/v4l2misc/v4l2misc.o: ../v4l2misc/v4l2misc.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../v4l2misc/v4l2misc.c -o $(OBJDIR_DEBUG)/v4l2misc/v4l2misc.o

$(OBJDIR_DEBUG)/v4l2misc/camview.o: ../v4l2misc/camview.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../v4l2misc/camview.cpp -o $(OBJDIR_DEBUG)/v4l2misc/camview.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf ./bin/Debug
	rm -rf $(OBJDIR_DEBUG)/Multiview/src
	rm -rf $(OBJDIR_DEBUG)/kbhit
	rm -rf $(OBJDIR_DEBUG)/v4l2misc

before_release: 
	test -d ./bin/Release || mkdir -p ./bin/Release
	test -d $(OBJDIR_RELEASE)/Multiview/src || mkdir -p $(OBJDIR_RELEASE)/Multiview/src
	test -d $(OBJDIR_RELEASE)/kbhit || mkdir -p $(OBJDIR_RELEASE)/kbhit
	test -d $(OBJDIR_RELEASE)/v4l2misc || mkdir -p $(OBJDIR_RELEASE)/v4l2misc

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/Multiview/src/process004.o: src/process004.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/process004.cpp -o $(OBJDIR_RELEASE)/Multiview/src/process004.o

$(OBJDIR_RELEASE)/Multiview/src/process003.o: src/process003.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/process003.cpp -o $(OBJDIR_RELEASE)/Multiview/src/process003.o

$(OBJDIR_RELEASE)/Multiview/src/process002.o: src/process002.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/process002.cpp -o $(OBJDIR_RELEASE)/Multiview/src/process002.o

$(OBJDIR_RELEASE)/Multiview/src/process001.o: src/process001.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/process001.cpp -o $(OBJDIR_RELEASE)/Multiview/src/process001.o

$(OBJDIR_RELEASE)/kbhit/kbhit.o: ../kbhit/kbhit.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../kbhit/kbhit.c -o $(OBJDIR_RELEASE)/kbhit/kbhit.o

$(OBJDIR_RELEASE)/Multiview/src/process000.o: src/process000.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/process000.cpp -o $(OBJDIR_RELEASE)/Multiview/src/process000.o

$(OBJDIR_RELEASE)/Multiview/src/multiview.o: src/multiview.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/multiview.cpp -o $(OBJDIR_RELEASE)/Multiview/src/multiview.o

$(OBJDIR_RELEASE)/v4l2misc/v4l2misc.o: ../v4l2misc/v4l2misc.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../v4l2misc/v4l2misc.c -o $(OBJDIR_RELEASE)/v4l2misc/v4l2misc.o

$(OBJDIR_RELEASE)/v4l2misc/camview.o: ../v4l2misc/camview.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../v4l2misc/camview.cpp -o $(OBJDIR_RELEASE)/v4l2misc/camview.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf ./bin/Release
	rm -rf $(OBJDIR_RELEASE)/Multiview/src
	rm -rf $(OBJDIR_RELEASE)/kbhit
	rm -rf $(OBJDIR_RELEASE)/v4l2misc

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

